# Generated by Django 2.2.5 on 2019-09-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(verbose_name='progress date'),
        ),
    ]
