# Generated by Django 2.2.5 on 2019-09-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190913_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='components',
            field=models.ManyToManyField(to='main_app.Component'),
        ),
    ]
